import type {
  Enrollment,
  MockExamConfig,
  MockResult,
  PayoutSummary,
  RevenueRecord,
  SellerCourse,
  SellerQuestion,
  SellerStudent,
  SellerStudioSnapshot,
} from "../../features/seller-dashboard/types";

const courses: SellerCourse[] = [
  {
    id: "course-aws-saa",
    slug: "aws-saa-c03-intensive",
    title: "AWS SAA-C03 Intensive",
    subtitle: "Architecture readiness bootcamp",
    description:
      "A complete exam prep path covering architecture patterns, reliability, and pricing-aware tradeoffs.",
    category: "Cloud Architecture",
    level: "intermediate",
    status: "published",
    updatedAt: "2026-04-07T08:10:00.000Z",
    publishedAt: "2026-02-14T09:30:00.000Z",
    pricing: {
      priceMinor: 14900,
      currency: "USD",
      discountPercent: 15,
      discountLabel: "Spring launch offer",
    },
  },
  {
    id: "course-aws-dva",
    slug: "aws-dva-c02-practical",
    title: "AWS DVA-C02 Practical",
    subtitle: "Developer exam crash track",
    description:
      "Hands-on developer-focused prep track for event-driven design, deployment flows, and debugging.",
    category: "Cloud Development",
    level: "intermediate",
    status: "draft",
    updatedAt: "2026-04-09T12:40:00.000Z",
    pricing: {
      priceMinor: 12900,
      currency: "USD",
      discountPercent: 0,
    },
  },
  {
    id: "course-az-104",
    slug: "azure-az104-operator",
    title: "Azure AZ-104 Operator",
    subtitle: "Administration and governance prep",
    description:
      "Operational Azure prep with identity, networking, monitoring, and governance scenarios.",
    category: "Cloud Administration",
    level: "beginner",
    status: "unpublished",
    updatedAt: "2026-04-08T10:10:00.000Z",
    publishedAt: "2026-03-22T09:15:00.000Z",
    pricing: {
      priceMinor: 9900,
      currency: "USD",
      discountPercent: 10,
      discountLabel: "Bundle unlock",
    },
  },
];

const questions: SellerQuestion[] = [
  {
    id: "q-saa-001",
    courseId: "course-aws-saa",
    status: "published",
    type: "single_choice",
    title: "VPC ingress design",
    questionText:
      "A workload in private subnets must expose a public HTTPS endpoint while preserving least privilege. What design is most appropriate?",
    prompt: "Select the best architecture pattern.",
    context: "Focus on network boundaries and managed ingress.",
    category: "Networking",
    keywords: ["vpc", "alb", "private-subnet", "security"],
    difficulty: "medium",
    marks: 2,
    options: [
      { id: "a", label: "A", text: "Expose EC2 instances directly with public IPs" },
      { id: "b", label: "B", text: "Use an ALB in public subnets and target private instances" },
      { id: "c", label: "C", text: "Use NAT Gateway as inbound endpoint" },
      { id: "d", label: "D", text: "Use private API Gateway without VPC link" },
    ],
    correctOptionIds: ["b"],
    explanation:
      "ALB in public subnets provides controlled ingress while workloads stay private.",
    createdAt: "2026-02-10T08:15:00.000Z",
    updatedAt: "2026-04-04T08:20:00.000Z",
    source: "manual",
  },
  {
    id: "q-saa-002",
    courseId: "course-aws-saa",
    status: "published",
    type: "multiple_choice",
    title: "Durability and resilience",
    questionText:
      "Select TWO architecture choices that improve durability for critical data.",
    prompt: "Choose exactly two options.",
    context: "Prioritize durability over latency.",
    category: "Storage",
    keywords: ["s3", "multi-az", "durability", "backup"],
    difficulty: "medium",
    marks: 3,
    options: [
      { id: "a", label: "A", text: "Store objects in S3 with versioning enabled" },
      { id: "b", label: "B", text: "Use single EC2 instance store only" },
      { id: "c", label: "C", text: "Cross-region backup replication" },
      { id: "d", label: "D", text: "Disable backup retention to reduce cost" },
    ],
    correctOptionIds: ["a", "c"],
    explanation:
      "Versioning and cross-region backup directly improve data durability objectives.",
    createdAt: "2026-02-12T09:00:00.000Z",
    updatedAt: "2026-04-05T11:10:00.000Z",
    source: "manual",
  },
  {
    id: "q-saa-003",
    courseId: "course-aws-saa",
    status: "draft",
    type: "single_choice",
    title: "Read-heavy scaling",
    questionText:
      "An OLTP database is overloaded by read traffic. Which option gives fastest low-risk relief?",
    prompt: "Pick one option.",
    context: "Assume minimal schema changes are preferred.",
    category: "Databases",
    keywords: ["rds", "read-replica", "scaling"],
    difficulty: "easy",
    marks: 2,
    options: [
      { id: "a", label: "A", text: "Move immediately to custom sharding" },
      { id: "b", label: "B", text: "Add read replicas and route reads" },
      { id: "c", label: "C", text: "Disable indexes" },
      { id: "d", label: "D", text: "Increase write batch size only" },
    ],
    correctOptionIds: ["b"],
    explanation: "Read replicas reduce read pressure with minimal application risk.",
    createdAt: "2026-03-01T08:40:00.000Z",
    updatedAt: "2026-04-09T09:05:00.000Z",
    source: "manual",
  },
  {
    id: "q-dva-001",
    courseId: "course-aws-dva",
    status: "draft",
    type: "single_choice",
    title: "Event integration",
    questionText:
      "A producer service must fan out events to multiple consumers asynchronously. Best fit?",
    prompt: "Select one service pattern.",
    context: "Aim for loosely-coupled eventing.",
    category: "Event-Driven",
    keywords: ["sns", "fanout", "async"],
    difficulty: "easy",
    marks: 1,
    options: [
      { id: "a", label: "A", text: "SNS topic with subscriber endpoints" },
      { id: "b", label: "B", text: "Synchronous REST call chain" },
      { id: "c", label: "C", text: "Single Lambda without trigger" },
      { id: "d", label: "D", text: "IAM role policy" },
    ],
    correctOptionIds: ["a"],
    explanation: "SNS is purpose-built for one-to-many asynchronous fan-out.",
    createdAt: "2026-03-15T11:20:00.000Z",
    updatedAt: "2026-04-08T11:00:00.000Z",
    source: "manual",
  },
  {
    id: "q-az-001",
    courseId: "course-az-104",
    status: "published",
    type: "multiple_choice",
    title: "Identity governance",
    questionText:
      "Choose TWO controls that tighten least-privilege posture in Azure.",
    prompt: "Select two best options.",
    context: "Governance-first administration.",
    category: "Identity",
    keywords: ["rbac", "pim", "governance"],
    difficulty: "medium",
    marks: 2,
    options: [
      { id: "a", label: "A", text: "Use RBAC custom roles by scope" },
      { id: "b", label: "B", text: "Grant owner at subscription to all engineers" },
      { id: "c", label: "C", text: "Enable PIM for privileged roles" },
      { id: "d", label: "D", text: "Share one root account" },
    ],
    correctOptionIds: ["a", "c"],
    explanation:
      "Scoped RBAC and PIM provide least privilege with auditable elevation.",
    createdAt: "2026-03-11T09:30:00.000Z",
    updatedAt: "2026-04-03T12:00:00.000Z",
    source: "manual",
  },
];

const mockExamConfigs: MockExamConfig[] = [
  {
    id: "mock-saa-01",
    courseId: "course-aws-saa",
    title: "SAA Foundation Mock 01",
    status: "published",
    questionCount: 65,
    durationMinutes: 130,
    passScore: 75,
    randomizeQuestions: true,
    questionIds: ["q-saa-001", "q-saa-002", "q-saa-003"],
    createdAt: "2026-02-20T08:00:00.000Z",
    updatedAt: "2026-04-05T07:20:00.000Z",
  },
  {
    id: "mock-saa-02",
    courseId: "course-aws-saa",
    title: "SAA Timed Drill 02",
    status: "draft",
    questionCount: 40,
    durationMinutes: 80,
    passScore: 78,
    randomizeQuestions: false,
    questionIds: ["q-saa-001", "q-saa-002"],
    createdAt: "2026-03-08T10:30:00.000Z",
    updatedAt: "2026-04-09T09:30:00.000Z",
  },
  {
    id: "mock-az-01",
    courseId: "course-az-104",
    title: "AZ-104 Readiness Mock",
    status: "unpublished",
    questionCount: 50,
    durationMinutes: 95,
    passScore: 72,
    randomizeQuestions: true,
    questionIds: ["q-az-001"],
    createdAt: "2026-03-19T08:40:00.000Z",
    updatedAt: "2026-04-08T09:00:00.000Z",
  },
];

const students: SellerStudent[] = [
  {
    id: "stu-01",
    name: "Maya Chen",
    email: "maya.chen@example.com",
    country: "US",
    joinedAt: "2026-01-12T09:10:00.000Z",
  },
  {
    id: "stu-02",
    name: "Liam Smith",
    email: "liam.smith@example.com",
    country: "UK",
    joinedAt: "2026-01-22T14:20:00.000Z",
  },
  {
    id: "stu-03",
    name: "Noah Alvarez",
    email: "noah.alvarez@example.com",
    country: "CA",
    joinedAt: "2026-02-02T10:05:00.000Z",
  },
  {
    id: "stu-04",
    name: "Ava Patel",
    email: "ava.patel@example.com",
    country: "IN",
    joinedAt: "2026-02-10T16:40:00.000Z",
  },
  {
    id: "stu-05",
    name: "Lucas Berg",
    email: "lucas.berg@example.com",
    country: "SE",
    joinedAt: "2026-03-03T08:25:00.000Z",
  },
  {
    id: "stu-06",
    name: "Sophia Williams",
    email: "sophia.williams@example.com",
    country: "AU",
    joinedAt: "2026-03-18T11:40:00.000Z",
  },
];

const enrollments: Enrollment[] = [
  {
    id: "enr-001",
    courseId: "course-aws-saa",
    studentId: "stu-01",
    enrolledAt: "2026-02-12T08:00:00.000Z",
    progressPercent: 84,
    completionPercent: 78,
    status: "active",
    lastActiveAt: "2026-04-09T19:00:00.000Z",
    totalAttempts: 9,
  },
  {
    id: "enr-002",
    courseId: "course-aws-saa",
    studentId: "stu-02",
    enrolledAt: "2026-02-16T09:10:00.000Z",
    progressPercent: 67,
    completionPercent: 58,
    status: "active",
    lastActiveAt: "2026-04-07T17:30:00.000Z",
    totalAttempts: 6,
  },
  {
    id: "enr-003",
    courseId: "course-aws-saa",
    studentId: "stu-03",
    enrolledAt: "2026-02-21T10:20:00.000Z",
    progressPercent: 93,
    completionPercent: 90,
    status: "completed",
    lastActiveAt: "2026-04-05T15:00:00.000Z",
    totalAttempts: 12,
  },
  {
    id: "enr-004",
    courseId: "course-az-104",
    studentId: "stu-04",
    enrolledAt: "2026-03-22T12:00:00.000Z",
    progressPercent: 42,
    completionPercent: 30,
    status: "active",
    lastActiveAt: "2026-04-08T20:00:00.000Z",
    totalAttempts: 3,
  },
  {
    id: "enr-005",
    courseId: "course-az-104",
    studentId: "stu-05",
    enrolledAt: "2026-03-26T09:00:00.000Z",
    progressPercent: 11,
    completionPercent: 5,
    status: "inactive",
    lastActiveAt: "2026-03-30T13:10:00.000Z",
    totalAttempts: 1,
  },
  {
    id: "enr-006",
    courseId: "course-aws-saa",
    studentId: "stu-06",
    enrolledAt: "2026-03-28T10:40:00.000Z",
    progressPercent: 51,
    completionPercent: 44,
    status: "active",
    lastActiveAt: "2026-04-09T08:45:00.000Z",
    totalAttempts: 4,
  },
];

const results: MockResult[] = [
  {
    id: "res-001",
    studentId: "stu-01",
    courseId: "course-aws-saa",
    mockExamId: "mock-saa-01",
    scorePercent: 81,
    passed: true,
    submittedAt: "2026-03-29T10:00:00.000Z",
    durationMinutes: 118,
  },
  {
    id: "res-002",
    studentId: "stu-01",
    courseId: "course-aws-saa",
    mockExamId: "mock-saa-01",
    scorePercent: 85,
    passed: true,
    submittedAt: "2026-04-07T12:10:00.000Z",
    durationMinutes: 115,
  },
  {
    id: "res-003",
    studentId: "stu-02",
    courseId: "course-aws-saa",
    mockExamId: "mock-saa-01",
    scorePercent: 72,
    passed: false,
    submittedAt: "2026-04-01T09:40:00.000Z",
    durationMinutes: 124,
  },
  {
    id: "res-004",
    studentId: "stu-03",
    courseId: "course-aws-saa",
    mockExamId: "mock-saa-01",
    scorePercent: 90,
    passed: true,
    submittedAt: "2026-04-04T14:20:00.000Z",
    durationMinutes: 109,
  },
  {
    id: "res-005",
    studentId: "stu-04",
    courseId: "course-az-104",
    mockExamId: "mock-az-01",
    scorePercent: 64,
    passed: false,
    submittedAt: "2026-04-08T11:50:00.000Z",
    durationMinutes: 87,
  },
  {
    id: "res-006",
    studentId: "stu-06",
    courseId: "course-aws-saa",
    mockExamId: "mock-saa-01",
    scorePercent: 76,
    passed: true,
    submittedAt: "2026-04-09T15:00:00.000Z",
    durationMinutes: 121,
  },
];

const revenueRecords: RevenueRecord[] = [
  {
    id: "rev-001",
    courseId: "course-aws-saa",
    studentId: "stu-01",
    grossMinor: 14900,
    discountMinor: 2235,
    netMinor: 12665,
    refunded: false,
    couponCode: "SPRING15",
    createdAt: "2026-02-12T08:00:00.000Z",
  },
  {
    id: "rev-002",
    courseId: "course-aws-saa",
    studentId: "stu-02",
    grossMinor: 14900,
    discountMinor: 0,
    netMinor: 14900,
    refunded: false,
    createdAt: "2026-02-16T09:10:00.000Z",
  },
  {
    id: "rev-003",
    courseId: "course-aws-saa",
    studentId: "stu-03",
    grossMinor: 14900,
    discountMinor: 2235,
    netMinor: 12665,
    refunded: false,
    couponCode: "SPRING15",
    createdAt: "2026-02-21T10:20:00.000Z",
  },
  {
    id: "rev-004",
    courseId: "course-az-104",
    studentId: "stu-04",
    grossMinor: 9900,
    discountMinor: 990,
    netMinor: 8910,
    refunded: false,
    couponCode: "AZ10",
    createdAt: "2026-03-22T12:00:00.000Z",
  },
  {
    id: "rev-005",
    courseId: "course-az-104",
    studentId: "stu-05",
    grossMinor: 9900,
    discountMinor: 990,
    netMinor: 8910,
    refunded: true,
    couponCode: "AZ10",
    createdAt: "2026-03-26T09:00:00.000Z",
  },
  {
    id: "rev-006",
    courseId: "course-aws-saa",
    studentId: "stu-06",
    grossMinor: 14900,
    discountMinor: 2235,
    netMinor: 12665,
    refunded: false,
    couponCode: "SPRING15",
    createdAt: "2026-03-28T10:40:00.000Z",
  },
];

const payouts: PayoutSummary[] = [
  {
    id: "payout-2026-02",
    periodLabel: "Feb 2026",
    grossMinor: 52265,
    feesMinor: 2350,
    netMinor: 49915,
    status: "paid",
    paidAt: "2026-03-03T09:30:00.000Z",
  },
  {
    id: "payout-2026-03",
    periodLabel: "Mar 2026",
    grossMinor: 39485,
    feesMinor: 1980,
    netMinor: 37505,
    status: "paid",
    paidAt: "2026-04-03T10:00:00.000Z",
  },
  {
    id: "payout-2026-04",
    periodLabel: "Apr 2026",
    grossMinor: 12665,
    feesMinor: 640,
    netMinor: 12025,
    status: "processing",
  },
];

export const sellerStudioSeed: SellerStudioSnapshot = {
  sellerId: "seller-demo",
  courses,
  questions,
  mockExamConfigs,
  students,
  enrollments,
  results,
  revenueRecords,
  payouts,
};
