BEGIN;

CREATE SCHEMA IF NOT EXISTS audit;
CREATE SCHEMA IF NOT EXISTS analytics;

DO $$
DECLARE
  rk "char";
BEGIN
  IF to_regclass('public.audit_events') IS NOT NULL THEN
    SELECT c.relkind INTO rk
    FROM pg_class c
    WHERE c.oid = 'public.audit_events'::regclass;

    IF rk = 'r' THEN
      IF to_regclass('public.audit_events_legacy') IS NULL THEN
        ALTER TABLE public.audit_events RENAME TO audit_events_legacy;
      ELSE
        INSERT INTO public.audit_events_legacy (
          id,
          organization_id,
          actor_user_id,
          actor_role,
          entity_table,
          entity_id,
          action,
          request_id,
          ip,
          user_agent,
          before_data,
          after_data,
          metadata,
          created_at
        )
        SELECT
          id,
          organization_id,
          actor_user_id,
          actor_role,
          entity_table,
          entity_id,
          action,
          request_id,
          ip,
          user_agent,
          before_data,
          after_data,
          metadata,
          created_at
        FROM public.audit_events src
        WHERE NOT EXISTS (
          SELECT 1
          FROM public.audit_events_legacy dst
          WHERE dst.id = src.id
        );
        DROP TABLE public.audit_events;
      END IF;
    END IF;
  END IF;

  IF to_regclass('public.analytics_events') IS NOT NULL THEN
    SELECT c.relkind INTO rk
    FROM pg_class c
    WHERE c.oid = 'public.analytics_events'::regclass;

    IF rk = 'r' THEN
      IF to_regclass('public.analytics_events_legacy') IS NULL THEN
        ALTER TABLE public.analytics_events RENAME TO analytics_events_legacy;
      ELSE
        INSERT INTO public.analytics_events_legacy (
          id,
          organization_id,
          user_id,
          session_id,
          event_name,
          event_time,
          properties
        )
        SELECT
          id,
          organization_id,
          user_id,
          session_id,
          event_name,
          event_time,
          properties
        FROM public.analytics_events src
        WHERE NOT EXISTS (
          SELECT 1
          FROM public.analytics_events_legacy dst
          WHERE dst.id = src.id
        );
        DROP TABLE public.analytics_events;
      END IF;
    END IF;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS audit.audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
  actor_user_id UUID REFERENCES public.app_users(id) ON DELETE SET NULL,
  actor_role app_role,
  entity_table TEXT NOT NULL,
  entity_id UUID,
  action TEXT NOT NULL,
  request_id UUID,
  ip INET,
  user_agent TEXT,
  before_data JSONB,
  after_data JSONB,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  PRIMARY KEY (created_at, id)
) PARTITION BY RANGE (created_at);

CREATE TABLE IF NOT EXISTS analytics.analytics_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  event_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  organization_id UUID NOT NULL REFERENCES public.organizations(id) ON DELETE RESTRICT,
  user_id UUID REFERENCES public.app_users(id) ON DELETE SET NULL,
  session_id UUID,
  event_name TEXT NOT NULL,
  properties JSONB NOT NULL DEFAULT '{}'::jsonb,
  PRIMARY KEY (event_time, id)
) PARTITION BY RANGE (event_time);

CREATE TABLE IF NOT EXISTS audit.audit_events_default
  PARTITION OF audit.audit_events DEFAULT;

CREATE TABLE IF NOT EXISTS analytics.analytics_events_default
  PARTITION OF analytics.analytics_events DEFAULT;

DO $$
BEGIN
  IF to_regclass('audit.audit_events') IS NOT NULL THEN
    ALTER TABLE audit.audit_events ALTER COLUMN id SET GENERATED BY DEFAULT;
  END IF;
  IF to_regclass('analytics.analytics_events') IS NOT NULL THEN
    ALTER TABLE analytics.analytics_events ALTER COLUMN id SET GENERATED BY DEFAULT;
  END IF;
END $$;

CREATE OR REPLACE FUNCTION app.ensure_event_monthly_partitions(months_back INT DEFAULT 1, months_ahead INT DEFAULT 12)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
  i INT;
  m_start DATE;
  m_end DATE;
  part_name TEXT;
BEGIN
  FOR i IN -months_back..months_ahead LOOP
    m_start := (date_trunc('month', NOW())::date + (i || ' month')::interval)::date;
    m_end := (m_start + INTERVAL '1 month')::date;

    part_name := format('audit_events_%s', to_char(m_start, 'YYYYMM'));
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS audit.%I PARTITION OF audit.audit_events FOR VALUES FROM (%L) TO (%L)',
      part_name, m_start::timestamptz, m_end::timestamptz
    );

    part_name := format('analytics_events_%s', to_char(m_start, 'YYYYMM'));
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS analytics.%I PARTITION OF analytics.analytics_events FOR VALUES FROM (%L) TO (%L)',
      part_name, m_start::timestamptz, m_end::timestamptz
    );
  END LOOP;
END;
$$;

SELECT app.ensure_event_monthly_partitions(2, 18);

DO $$
BEGIN
  IF to_regclass('public.audit_events_legacy') IS NOT NULL THEN
    INSERT INTO audit.audit_events (
      id,
      created_at,
      organization_id,
      actor_user_id,
      actor_role,
      entity_table,
      entity_id,
      action,
      request_id,
      ip,
      user_agent,
      before_data,
      after_data,
      metadata
    )
    SELECT
      id,
      created_at,
      organization_id,
      actor_user_id,
      actor_role,
      entity_table,
      entity_id,
      action,
      request_id,
      ip,
      user_agent,
      before_data,
      after_data,
      metadata
    FROM public.audit_events_legacy
    ON CONFLICT (created_at, id) DO NOTHING;
  END IF;

  IF to_regclass('public.analytics_events_legacy') IS NOT NULL THEN
    INSERT INTO analytics.analytics_events (
      id,
      event_time,
      organization_id,
      user_id,
      session_id,
      event_name,
      properties
    )
    SELECT
      id,
      event_time,
      organization_id,
      user_id,
      session_id,
      event_name,
      properties
    FROM public.analytics_events_legacy
    ON CONFLICT (event_time, id) DO NOTHING;
  END IF;
END $$;

DO $$
DECLARE
  seq_name TEXT;
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='audit' AND table_name='audit_events' AND column_name='id') THEN
    seq_name := pg_get_serial_sequence('audit.audit_events', 'id');
    IF seq_name IS NOT NULL THEN
      PERFORM setval(
        seq_name,
        COALESCE((SELECT MAX(id) FROM audit.audit_events), 0) + 1,
        false
      );
    END IF;
  END IF;

  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='analytics' AND table_name='analytics_events' AND column_name='id') THEN
    seq_name := pg_get_serial_sequence('analytics.analytics_events', 'id');
    IF seq_name IS NOT NULL THEN
      PERFORM setval(
        seq_name,
        COALESCE((SELECT MAX(id) FROM analytics.analytics_events), 0) + 1,
        false
      );
    END IF;
  END IF;
END $$;

DO $$
DECLARE
  rk "char";
BEGIN
  IF to_regclass('public.audit_events') IS NOT NULL THEN
    SELECT c.relkind INTO rk
    FROM pg_class c
    WHERE c.oid = 'public.audit_events'::regclass;
    IF rk = 'v' THEN
      DROP VIEW public.audit_events;
    ELSIF rk = 'm' THEN
      DROP MATERIALIZED VIEW public.audit_events;
    END IF;
  END IF;

  IF to_regclass('public.analytics_events') IS NOT NULL THEN
    SELECT c.relkind INTO rk
    FROM pg_class c
    WHERE c.oid = 'public.analytics_events'::regclass;
    IF rk = 'v' THEN
      DROP VIEW public.analytics_events;
    ELSIF rk = 'm' THEN
      DROP MATERIALIZED VIEW public.analytics_events;
    END IF;
  END IF;
END $$;

DO $$
BEGIN
  BEGIN
    EXECUTE $sql$
      CREATE VIEW public.audit_events
      WITH (security_invoker = true)
      AS
      SELECT *
      FROM audit.audit_events
    $sql$;
  EXCEPTION
    WHEN syntax_error_or_access_rule_violation THEN
      NULL;
    WHEN feature_not_supported THEN
      NULL;
  END;

  BEGIN
    EXECUTE $sql$
      CREATE VIEW public.analytics_events
      WITH (security_invoker = true)
      AS
      SELECT *
      FROM analytics.analytics_events
    $sql$;
  EXCEPTION
    WHEN syntax_error_or_access_rule_violation THEN
      NULL;
    WHEN feature_not_supported THEN
      NULL;
  END;
END $$;

DO $$
BEGIN
  IF to_regclass('public.audit_events') IS NOT NULL THEN
    COMMENT ON VIEW public.audit_events IS 'Compatibility view for partitioned audit.audit_events (security_invoker).';
  END IF;
  IF to_regclass('public.analytics_events') IS NOT NULL THEN
    COMMENT ON VIEW public.analytics_events IS 'Compatibility view for partitioned analytics.analytics_events (security_invoker).';
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'prephatch_create_event_partitions') THEN
      PERFORM cron.unschedule((SELECT jobid FROM cron.job WHERE jobname = 'prephatch_create_event_partitions' LIMIT 1));
    END IF;

    PERFORM cron.schedule(
      'prephatch_create_event_partitions',
      '10 0 1 * *',
      'SELECT app.ensure_event_monthly_partitions(2, 18);'
    );
  END IF;
EXCEPTION
  WHEN undefined_table THEN
    NULL;
  WHEN undefined_function THEN
    NULL;
  WHEN insufficient_privilege THEN
    NULL;
END $$;

COMMIT;
